---
EnableDefaultLinters: true
linters:
  ErbSafety:
    enabled: false
  Rubocop:
    enabled: false
  NoJavaScriptTagHelper:
    enabled: false
  RightTrim:
    enabled: false
  SelfClosingTag:
    enabled: false
  ExtraWhitespace:
    enabled: false
  FinalNewline:
    enabled: false
  TrailingWhitespace:
    enabled: false
  ParserErrors:
    enabled: false

exclude:
  - "app/views/**/*.html.erb"
