# MongoDB configuration for OneLastAI
development:
  clients:
    default:
      database: onelastai_development
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1

test:
  clients:
    default:
      database: onelastai_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        max_pool_size: <%= ENV['MONGODB_POOL_SIZE'] || 20 %>
        min_pool_size: 1
        wait_queue_timeout: <%= ENV['MONGODB_TIMEOUT'] || 10 %>
        connect_timeout: 10
        socket_timeout: 5
        ssl: true
        ssl_verify: true
        heartbeat_frequency: 10
        # Retry writes for better reliability
        retry_writes: true
        # Write concern for data durability
        write:
          w: :majority
          j: true
        # Read preference for performance
        read:
          mode: :secondary_preferred
          max_staleness_seconds: 120